Update sync_fork.yml

diff --git a/.github/workflows/sync_fork.yml b/.github/workflows/sync_fork.yml
--- a/.github/workflows/sync_fork.yml
+++ b/.github/workflows/sync_fork.yml
@@ -1,7 +1,11 @@
-name: 'Fork Sync'
+name: Fork Sync
+
+permissions:
+  contents: write
+
 on:
   schedule:
-    - cron: '20 4 * * *'
+    - cron: '33 3 * * *'
   workflow_dispatch:
     inputs:
       sync_test_mode:
@@ -13,43 +17,26 @@ jobs:
   sync_latest_from_upstream:
     name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
+
     steps:
+      # Step 1: run a standard checkout action
       - name: Checkout target repo
         uses: actions/checkout@v6
-        with:
-          ref: main
-          persist-credentials: false
 
+      # Step 2: run the sync action
       - name: Sync upstream changes
         id: sync
-        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        uses: aormsby/fork-sync-with-upstream-action@v3.4
         with:
-          target_sync_branch: main
-          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
-          upstream_sync_branch: main
           upstream_sync_repo: cmliu/edgetunnel
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
           test_mode: ${{ inputs.sync_test_mode }}
 
-      - name: Generate wrangler.toml
-        if: (steps.sync.outputs.has_new_commits == 'true' || github.event_name == 'workflow_dispatch') && inputs.sync_test_mode != true
+      - name: Sync check
+        if: failure()
         run: |
-          cat > wrangler.toml << 'EOF'
-          name = "fuck"
-          main = "_worker.js"
-          compatibility_date = "2025-11-04"
-          [[kv_namespaces]]
-          binding = "KV"
-          id = "${{ vars.FUCK_KV_ID }}"
-          [vars]
-          ADMIN = "${{ secrets.ADMIN_PASSWORD }}"
-          KEY = "${{ vars.UUID }}"
-          UUID = "${{ vars.UUID }}"
-          URL = "${{ vars.URL }}"
-          EOF
-
-      - name: Deploy to Cloudflare Workers
-        if: (steps.sync.outputs.has_new_commits == 'true' || github.event_name == 'workflow_dispatch') && inputs.sync_test_mode != true
-        uses: cloudflare/wrangler-action@v3
-        with:
-          apiToken: ${{ secrets.CF_API_TOKEN }}
-          accountId: ${{ secrets.CF_ACCOUNT_ID }}
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次."
+          exit 1
